//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeEditor) DeepCopyInto(out *CodeEditor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeEditor.
func (in *CodeEditor) DeepCopy() *CodeEditor {
	if in == nil {
		return nil
	}
	out := new(CodeEditor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeEditor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeEditorList) DeepCopyInto(out *CodeEditorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CodeEditor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeEditorList.
func (in *CodeEditorList) DeepCopy() *CodeEditorList {
	if in == nil {
		return nil
	}
	out := new(CodeEditorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeEditorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeEditorSpec) DeepCopyInto(out *CodeEditorSpec) {
	*out = *in
	if in.VolumeClaimTemplates != nil {
		in, out := &in.VolumeClaimTemplates, &out.VolumeClaimTemplates
		*out = make([]v1.PersistentVolumeClaimTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeEditorSpec.
func (in *CodeEditorSpec) DeepCopy() *CodeEditorSpec {
	if in == nil {
		return nil
	}
	out := new(CodeEditorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeEditorStatus) DeepCopyInto(out *CodeEditorStatus) {
	*out = *in
	if in.PVCStatuses != nil {
		in, out := &in.PVCStatuses, &out.PVCStatuses
		*out = make([]OwnedPVCStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeEditorStatus.
func (in *CodeEditorStatus) DeepCopy() *CodeEditorStatus {
	if in == nil {
		return nil
	}
	out := new(CodeEditorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchContainer) DeepCopyInto(out *LaunchContainer) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Container.DeepCopyInto(&out.Container)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchContainer.
func (in *LaunchContainer) DeepCopy() *LaunchContainer {
	if in == nil {
		return nil
	}
	out := new(LaunchContainer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedPVCStatus) DeepCopyInto(out *OwnedPVCStatus) {
	*out = *in
	out.Resource = in.Resource
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedPVCStatus.
func (in *OwnedPVCStatus) DeepCopy() *OwnedPVCStatus {
	if in == nil {
		return nil
	}
	out := new(OwnedPVCStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedResourceStatus) DeepCopyInto(out *OwnedResourceStatus) {
	*out = *in
	out.Reference = in.Reference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedResourceStatus.
func (in *OwnedResourceStatus) DeepCopy() *OwnedResourceStatus {
	if in == nil {
		return nil
	}
	out := new(OwnedResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedStatefulSetStatus) DeepCopyInto(out *OwnedStatefulSetStatus) {
	*out = *in
	out.Resource = in.Resource
	in.Status.DeepCopyInto(&out.Status)
	if in.ContainerStatuses != nil {
		in, out := &in.ContainerStatuses, &out.ContainerStatuses
		*out = make([]v1.ContainerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedStatefulSetStatus.
func (in *OwnedStatefulSetStatus) DeepCopy() *OwnedStatefulSetStatus {
	if in == nil {
		return nil
	}
	out := new(OwnedStatefulSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROS2Bridge) DeepCopyInto(out *ROS2Bridge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROS2Bridge.
func (in *ROS2Bridge) DeepCopy() *ROS2Bridge {
	if in == nil {
		return nil
	}
	out := new(ROS2Bridge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ROS2Bridge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROS2BridgeInstanceStatus) DeepCopyInto(out *ROS2BridgeInstanceStatus) {
	*out = *in
	out.Resource = in.Resource
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROS2BridgeInstanceStatus.
func (in *ROS2BridgeInstanceStatus) DeepCopy() *ROS2BridgeInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ROS2BridgeInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROS2BridgeList) DeepCopyInto(out *ROS2BridgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ROS2Bridge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROS2BridgeList.
func (in *ROS2BridgeList) DeepCopy() *ROS2BridgeList {
	if in == nil {
		return nil
	}
	out := new(ROS2BridgeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ROS2BridgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROS2BridgeSpec) DeepCopyInto(out *ROS2BridgeSpec) {
	*out = *in
	out.DiscoveryServerReference = in.DiscoveryServerReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROS2BridgeSpec.
func (in *ROS2BridgeSpec) DeepCopy() *ROS2BridgeSpec {
	if in == nil {
		return nil
	}
	out := new(ROS2BridgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROS2BridgeStatus) DeepCopyInto(out *ROS2BridgeStatus) {
	*out = *in
	out.ConnectionInfo = in.ConnectionInfo
	out.PodStatus = in.PodStatus
	in.ServiceStatus.DeepCopyInto(&out.ServiceStatus)
	out.IngressStatus = in.IngressStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROS2BridgeStatus.
func (in *ROS2BridgeStatus) DeepCopy() *ROS2BridgeStatus {
	if in == nil {
		return nil
	}
	out := new(ROS2BridgeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROS2Workload) DeepCopyInto(out *ROS2Workload) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROS2Workload.
func (in *ROS2Workload) DeepCopy() *ROS2Workload {
	if in == nil {
		return nil
	}
	out := new(ROS2Workload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ROS2Workload) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROS2WorkloadList) DeepCopyInto(out *ROS2WorkloadList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ROS2Workload, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROS2WorkloadList.
func (in *ROS2WorkloadList) DeepCopy() *ROS2WorkloadList {
	if in == nil {
		return nil
	}
	out := new(ROS2WorkloadList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ROS2WorkloadList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROS2WorkloadSpec) DeepCopyInto(out *ROS2WorkloadSpec) {
	*out = *in
	out.DiscoveryServerTemplate = in.DiscoveryServerTemplate
	out.ROS2BridgeTemplate = in.ROS2BridgeTemplate
	if in.VolumeClaimTemplates != nil {
		in, out := &in.VolumeClaimTemplates, &out.VolumeClaimTemplates
		*out = make([]v1.PersistentVolumeClaimTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LaunchContainers != nil {
		in, out := &in.LaunchContainers, &out.LaunchContainers
		*out = make([]LaunchContainer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROS2WorkloadSpec.
func (in *ROS2WorkloadSpec) DeepCopy() *ROS2WorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(ROS2WorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROS2WorkloadStatus) DeepCopyInto(out *ROS2WorkloadStatus) {
	*out = *in
	out.DiscoveryServerStatus = in.DiscoveryServerStatus
	in.ROS2BridgeStatus.DeepCopyInto(&out.ROS2BridgeStatus)
	if in.PVCStatuses != nil {
		in, out := &in.PVCStatuses, &out.PVCStatuses
		*out = make([]OwnedPVCStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StatefulSetStatuses != nil {
		in, out := &in.StatefulSetStatuses, &out.StatefulSetStatuses
		*out = make([]OwnedStatefulSetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROS2WorkloadStatus.
func (in *ROS2WorkloadStatus) DeepCopy() *ROS2WorkloadStatus {
	if in == nil {
		return nil
	}
	out := new(ROS2WorkloadStatus)
	in.DeepCopyInto(out)
	return out
}
