//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdditionalConfig) DeepCopyInto(out *AdditionalConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdditionalConfig.
func (in *AdditionalConfig) DeepCopy() *AdditionalConfig {
	if in == nil {
		return nil
	}
	out := new(AdditionalConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachedBuildObject) DeepCopyInto(out *AttachedBuildObject) {
	*out = *in
	out.Reference = in.Reference
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachedBuildObject.
func (in *AttachedBuildObject) DeepCopy() *AttachedBuildObject {
	if in == nil {
		return nil
	}
	out := new(AttachedBuildObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachedDevObject) DeepCopyInto(out *AttachedDevObject) {
	*out = *in
	out.Reference = in.Reference
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachedDevObject.
func (in *AttachedDevObject) DeepCopy() *AttachedDevObject {
	if in == nil {
		return nil
	}
	out := new(AttachedDevObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttachedLaunchObject) DeepCopyInto(out *AttachedLaunchObject) {
	*out = *in
	out.Reference = in.Reference
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttachedLaunchObject.
func (in *AttachedLaunchObject) DeepCopy() *AttachedLaunchObject {
	if in == nil {
		return nil
	}
	out := new(AttachedLaunchObject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeDistro) DeepCopyInto(out *BridgeDistro) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeDistro.
func (in *BridgeDistro) DeepCopy() *BridgeDistro {
	if in == nil {
		return nil
	}
	out := new(BridgeDistro)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildManager) DeepCopyInto(out *BuildManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildManager.
func (in *BuildManager) DeepCopy() *BuildManager {
	if in == nil {
		return nil
	}
	out := new(BuildManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BuildManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildManagerList) DeepCopyInto(out *BuildManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BuildManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildManagerList.
func (in *BuildManagerList) DeepCopy() *BuildManagerList {
	if in == nil {
		return nil
	}
	out := new(BuildManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BuildManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildManagerSpec) DeepCopyInto(out *BuildManagerSpec) {
	*out = *in
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]Step, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildManagerSpec.
func (in *BuildManagerSpec) DeepCopy() *BuildManagerSpec {
	if in == nil {
		return nil
	}
	out := new(BuildManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildManagerStatus) DeepCopyInto(out *BuildManagerStatus) {
	*out = *in
	out.ScriptConfigMapStatus = in.ScriptConfigMapStatus
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]StepStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildManagerStatus.
func (in *BuildManagerStatus) DeepCopy() *BuildManagerStatus {
	if in == nil {
		return nil
	}
	out := new(BuildManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionInfo) DeepCopyInto(out *ConnectionInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionInfo.
func (in *ConnectionInfo) DeepCopy() *ConnectionInfo {
	if in == nil {
		return nil
	}
	out := new(ConnectionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevSpaceImage) DeepCopyInto(out *DevSpaceImage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevSpaceImage.
func (in *DevSpaceImage) DeepCopy() *DevSpaceImage {
	if in == nil {
		return nil
	}
	out := new(DevSpaceImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServer) DeepCopyInto(out *DiscoveryServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServer.
func (in *DiscoveryServer) DeepCopy() *DiscoveryServer {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServerInstanceStatus) DeepCopyInto(out *DiscoveryServerInstanceStatus) {
	*out = *in
	out.Resource = in.Resource
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServerInstanceStatus.
func (in *DiscoveryServerInstanceStatus) DeepCopy() *DiscoveryServerInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServerInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServerList) DeepCopyInto(out *DiscoveryServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiscoveryServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServerList.
func (in *DiscoveryServerList) DeepCopy() *DiscoveryServerList {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiscoveryServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServerSpec) DeepCopyInto(out *DiscoveryServerSpec) {
	*out = *in
	out.Reference = in.Reference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServerSpec.
func (in *DiscoveryServerSpec) DeepCopy() *DiscoveryServerSpec {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryServerStatus) DeepCopyInto(out *DiscoveryServerStatus) {
	*out = *in
	out.ServiceStatus = in.ServiceStatus
	out.ServiceExportStatus = in.ServiceExportStatus
	out.PodStatus = in.PodStatus
	out.ConfigMapStatus = in.ConfigMapStatus
	out.ConnectionInfo = in.ConnectionInfo
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryServerStatus.
func (in *DiscoveryServerStatus) DeepCopy() *DiscoveryServerStatus {
	if in == nil {
		return nil
	}
	out := new(DiscoveryServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentConfig) DeepCopyInto(out *EnvironmentConfig) {
	*out = *in
	out.Application = in.Application
	out.DevSpaceImage = in.DevSpaceImage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentConfig.
func (in *EnvironmentConfig) DeepCopy() *EnvironmentConfig {
	if in == nil {
		return nil
	}
	out := new(EnvironmentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDevice) DeepCopyInto(out *GPUDevice) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDevice.
func (in *GPUDevice) DeepCopy() *GPUDevice {
	if in == nil {
		return nil
	}
	out := new(GPUDevice)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceMetrics) DeepCopyInto(out *GPUDeviceMetrics) {
	*out = *in
	if in.Temp != nil {
		in, out := &in.Temp, &out.Temp
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PowerUsage != nil {
		in, out := &in.PowerUsage, &out.PowerUsage
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GPUUtil != nil {
		in, out := &in.GPUUtil, &out.GPUUtil
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MemoryUtil != nil {
		in, out := &in.MemoryUtil, &out.MemoryUtil
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FramebufferMemoryFree != nil {
		in, out := &in.FramebufferMemoryFree, &out.FramebufferMemoryFree
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.FramebufferMemoryUsed != nil {
		in, out := &in.FramebufferMemoryUsed, &out.FramebufferMemoryUsed
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceMetrics.
func (in *GPUDeviceMetrics) DeepCopy() *GPUDeviceMetrics {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUDeviceStatuses) DeepCopyInto(out *GPUDeviceStatuses) {
	*out = *in
	if in.Devices != nil {
		in, out := &in.Devices, &out.Devices
		*out = make(map[string]GPUDevice, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Metrics.DeepCopyInto(&out.Metrics)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUDeviceStatuses.
func (in *GPUDeviceStatuses) DeepCopy() *GPUDeviceStatuses {
	if in == nil {
		return nil
	}
	out := new(GPUDeviceStatuses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUInstanceStatus) DeepCopyInto(out *GPUInstanceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUInstanceStatus.
func (in *GPUInstanceStatus) DeepCopy() *GPUInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(GPUInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUMetrics) DeepCopyInto(out *GPUMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUMetrics.
func (in *GPUMetrics) DeepCopy() *GPUMetrics {
	if in == nil {
		return nil
	}
	out := new(GPUMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUUtilizationStatus) DeepCopyInto(out *GPUUtilizationStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUUtilizationStatus.
func (in *GPUUtilizationStatus) DeepCopy() *GPUUtilizationStatus {
	if in == nil {
		return nil
	}
	out := new(GPUUtilizationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostDirectory) DeepCopyInto(out *HostDirectory) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostDirectory.
func (in *HostDirectory) DeepCopy() *HostDirectory {
	if in == nil {
		return nil
	}
	out := new(HostDirectory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Launch) DeepCopyInto(out *Launch) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Entrypoint.DeepCopyInto(&out.Entrypoint)
	in.Container.DeepCopyInto(&out.Container)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Launch.
func (in *Launch) DeepCopy() *Launch {
	if in == nil {
		return nil
	}
	out := new(Launch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchContainerConfig) DeepCopyInto(out *LaunchContainerConfig) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchContainerConfig.
func (in *LaunchContainerConfig) DeepCopy() *LaunchContainerConfig {
	if in == nil {
		return nil
	}
	out := new(LaunchContainerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchEntrypointConfig) DeepCopyInto(out *LaunchEntrypointConfig) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchEntrypointConfig.
func (in *LaunchEntrypointConfig) DeepCopy() *LaunchEntrypointConfig {
	if in == nil {
		return nil
	}
	out := new(LaunchEntrypointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchManager) DeepCopyInto(out *LaunchManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchManager.
func (in *LaunchManager) DeepCopy() *LaunchManager {
	if in == nil {
		return nil
	}
	out := new(LaunchManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LaunchManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchManagerList) DeepCopyInto(out *LaunchManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LaunchManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchManagerList.
func (in *LaunchManagerList) DeepCopy() *LaunchManagerList {
	if in == nil {
		return nil
	}
	out := new(LaunchManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LaunchManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchManagerSpec) DeepCopyInto(out *LaunchManagerSpec) {
	*out = *in
	if in.Launches != nil {
		in, out := &in.Launches, &out.Launches
		*out = make(map[string]Launch, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchManagerSpec.
func (in *LaunchManagerSpec) DeepCopy() *LaunchManagerSpec {
	if in == nil {
		return nil
	}
	out := new(LaunchManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchManagerStatus) DeepCopyInto(out *LaunchManagerStatus) {
	*out = *in
	in.LaunchPodStatus.DeepCopyInto(&out.LaunchPodStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchManagerStatus.
func (in *LaunchManagerStatus) DeepCopy() *LaunchManagerStatus {
	if in == nil {
		return nil
	}
	out := new(LaunchManagerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchPodStatus) DeepCopyInto(out *LaunchPodStatus) {
	*out = *in
	out.Status = in.Status
	if in.LaunchStatus != nil {
		in, out := &in.LaunchStatus, &out.LaunchStatus
		*out = make(map[string]LaunchStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchPodStatus.
func (in *LaunchPodStatus) DeepCopy() *LaunchPodStatus {
	if in == nil {
		return nil
	}
	out := new(LaunchPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LaunchStatus) DeepCopyInto(out *LaunchStatus) {
	*out = *in
	in.ContainerStatus.DeepCopyInto(&out.ContainerStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LaunchStatus.
func (in *LaunchStatus) DeepCopy() *LaunchStatus {
	if in == nil {
		return nil
	}
	out := new(LaunchStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsExporter) DeepCopyInto(out *MetricsExporter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsExporter.
func (in *MetricsExporter) DeepCopy() *MetricsExporter {
	if in == nil {
		return nil
	}
	out := new(MetricsExporter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetricsExporter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsExporterList) DeepCopyInto(out *MetricsExporterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MetricsExporter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsExporterList.
func (in *MetricsExporterList) DeepCopy() *MetricsExporterList {
	if in == nil {
		return nil
	}
	out := new(MetricsExporterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MetricsExporterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsExporterSpec) DeepCopyInto(out *MetricsExporterSpec) {
	*out = *in
	out.GPU = in.GPU
	in.Network.DeepCopyInto(&out.Network)
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsExporterSpec.
func (in *MetricsExporterSpec) DeepCopy() *MetricsExporterSpec {
	if in == nil {
		return nil
	}
	out := new(MetricsExporterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsExporterStatus) DeepCopyInto(out *MetricsExporterStatus) {
	*out = *in
	out.RoleStatus = in.RoleStatus
	out.RoleBindingStatus = in.RoleBindingStatus
	out.ServiceAccountStatus = in.ServiceAccountStatus
	out.PodStatus = in.PodStatus
	in.Usage.DeepCopyInto(&out.Usage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsExporterStatus.
func (in *MetricsExporterStatus) DeepCopy() *MetricsExporterStatus {
	if in == nil {
		return nil
	}
	out := new(MetricsExporterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceLoad) DeepCopyInto(out *NetworkInterfaceLoad) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceLoad.
func (in *NetworkInterfaceLoad) DeepCopy() *NetworkInterfaceLoad {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceLoad)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkLoadStatus) DeepCopyInto(out *NetworkLoadStatus) {
	*out = *in
	if in.Load != nil {
		in, out := &in.Load, &out.Load
		*out = make(map[string]NetworkInterfaceLoad, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkLoadStatus.
func (in *NetworkLoadStatus) DeepCopy() *NetworkLoadStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkLoadStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkMetrics) DeepCopyInto(out *NetworkMetrics) {
	*out = *in
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkMetrics.
func (in *NetworkMetrics) DeepCopy() *NetworkMetrics {
	if in == nil {
		return nil
	}
	out := new(NetworkMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedPodStatus) DeepCopyInto(out *OwnedPodStatus) {
	*out = *in
	out.Resource = in.Resource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedPodStatus.
func (in *OwnedPodStatus) DeepCopy() *OwnedPodStatus {
	if in == nil {
		return nil
	}
	out := new(OwnedPodStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedResourceStatus) DeepCopyInto(out *OwnedResourceStatus) {
	*out = *in
	out.Reference = in.Reference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedResourceStatus.
func (in *OwnedResourceStatus) DeepCopy() *OwnedResourceStatus {
	if in == nil {
		return nil
	}
	out := new(OwnedResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedRobotServiceStatus) DeepCopyInto(out *OwnedRobotServiceStatus) {
	*out = *in
	out.Resource = in.Resource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedRobotServiceStatus.
func (in *OwnedRobotServiceStatus) DeepCopy() *OwnedRobotServiceStatus {
	if in == nil {
		return nil
	}
	out := new(OwnedRobotServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OwnedServiceStatus) DeepCopyInto(out *OwnedServiceStatus) {
	*out = *in
	out.Resource = in.Resource
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OwnedServiceStatus.
func (in *OwnedServiceStatus) DeepCopy() *OwnedServiceStatus {
	if in == nil {
		return nil
	}
	out := new(OwnedServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentDirectory) DeepCopyInto(out *PersistentDirectory) {
	*out = *in
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentDirectory.
func (in *PersistentDirectory) DeepCopy() *PersistentDirectory {
	if in == nil {
		return nil
	}
	out := new(PersistentDirectory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROSBridge) DeepCopyInto(out *ROSBridge) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROSBridge.
func (in *ROSBridge) DeepCopy() *ROSBridge {
	if in == nil {
		return nil
	}
	out := new(ROSBridge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ROSBridge) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROSBridgeInstanceStatus) DeepCopyInto(out *ROSBridgeInstanceStatus) {
	*out = *in
	out.Resource = in.Resource
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROSBridgeInstanceStatus.
func (in *ROSBridgeInstanceStatus) DeepCopy() *ROSBridgeInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(ROSBridgeInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROSBridgeList) DeepCopyInto(out *ROSBridgeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ROSBridge, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROSBridgeList.
func (in *ROSBridgeList) DeepCopy() *ROSBridgeList {
	if in == nil {
		return nil
	}
	out := new(ROSBridgeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ROSBridgeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROSBridgeSpec) DeepCopyInto(out *ROSBridgeSpec) {
	*out = *in
	out.ROS = in.ROS
	out.ROS2 = in.ROS2
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROSBridgeSpec.
func (in *ROSBridgeSpec) DeepCopy() *ROSBridgeSpec {
	if in == nil {
		return nil
	}
	out := new(ROSBridgeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ROSBridgeStatus) DeepCopyInto(out *ROSBridgeStatus) {
	*out = *in
	out.PodStatus = in.PodStatus
	out.ServiceStatus = in.ServiceStatus
	out.IngressStatus = in.IngressStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ROSBridgeStatus.
func (in *ROSBridgeStatus) DeepCopy() *ROSBridgeStatus {
	if in == nil {
		return nil
	}
	out := new(ROSBridgeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelayServer) DeepCopyInto(out *RelayServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelayServer.
func (in *RelayServer) DeepCopy() *RelayServer {
	if in == nil {
		return nil
	}
	out := new(RelayServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RelayServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelayServerList) DeepCopyInto(out *RelayServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RelayServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelayServerList.
func (in *RelayServerList) DeepCopy() *RelayServerList {
	if in == nil {
		return nil
	}
	out := new(RelayServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RelayServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelayServerSpec) DeepCopyInto(out *RelayServerSpec) {
	*out = *in
	out.RootDNSConfig = in.RootDNSConfig
	out.TLSSecretReference = in.TLSSecretReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelayServerSpec.
func (in *RelayServerSpec) DeepCopy() *RelayServerSpec {
	if in == nil {
		return nil
	}
	out := new(RelayServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelayServerStatus) DeepCopyInto(out *RelayServerStatus) {
	*out = *in
	out.PodStatus = in.PodStatus
	out.ServiceStatus = in.ServiceStatus
	out.IngressStatus = in.IngressStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelayServerStatus.
func (in *RelayServerStatus) DeepCopy() *RelayServerStatus {
	if in == nil {
		return nil
	}
	out := new(RelayServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Repository) DeepCopyInto(out *Repository) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Repository.
func (in *Repository) DeepCopy() *Repository {
	if in == nil {
		return nil
	}
	out := new(Repository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resources) DeepCopyInto(out *Resources) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resources.
func (in *Resources) DeepCopy() *Resources {
	if in == nil {
		return nil
	}
	out := new(Resources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Robot) DeepCopyInto(out *Robot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Robot.
func (in *Robot) DeepCopy() *Robot {
	if in == nil {
		return nil
	}
	out := new(Robot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Robot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotArtifact) DeepCopyInto(out *RobotArtifact) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotArtifact.
func (in *RobotArtifact) DeepCopy() *RobotArtifact {
	if in == nil {
		return nil
	}
	out := new(RobotArtifact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RobotArtifact) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotArtifactList) DeepCopyInto(out *RobotArtifactList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RobotArtifact, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotArtifactList.
func (in *RobotArtifactList) DeepCopy() *RobotArtifactList {
	if in == nil {
		return nil
	}
	out := new(RobotArtifactList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RobotArtifactList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotConfig) DeepCopyInto(out *RobotConfig) {
	*out = *in
	if in.Distributions != nil {
		in, out := &in.Distributions, &out.Distributions
		*out = make([]ROSDistro, len(*in))
		copy(*out, *in)
	}
	out.DiscoveryServerTemplate = in.DiscoveryServerTemplate
	out.ROSBridgeTemplate = in.ROSBridgeTemplate
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotConfig.
func (in *RobotConfig) DeepCopy() *RobotConfig {
	if in == nil {
		return nil
	}
	out := new(RobotConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotDevSuite) DeepCopyInto(out *RobotDevSuite) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotDevSuite.
func (in *RobotDevSuite) DeepCopy() *RobotDevSuite {
	if in == nil {
		return nil
	}
	out := new(RobotDevSuite)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RobotDevSuite) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotDevSuiteInstanceStatus) DeepCopyInto(out *RobotDevSuiteInstanceStatus) {
	*out = *in
	out.Resource = in.Resource
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotDevSuiteInstanceStatus.
func (in *RobotDevSuiteInstanceStatus) DeepCopy() *RobotDevSuiteInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(RobotDevSuiteInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotDevSuiteList) DeepCopyInto(out *RobotDevSuiteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RobotDevSuite, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotDevSuiteList.
func (in *RobotDevSuiteList) DeepCopy() *RobotDevSuiteList {
	if in == nil {
		return nil
	}
	out := new(RobotDevSuiteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RobotDevSuiteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotDevSuiteSpec) DeepCopyInto(out *RobotDevSuiteSpec) {
	*out = *in
	out.RobotVDITemplate = in.RobotVDITemplate
	out.RobotIDETemplate = in.RobotIDETemplate
	out.RemoteIDERelayServerTemplate = in.RemoteIDERelayServerTemplate
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotDevSuiteSpec.
func (in *RobotDevSuiteSpec) DeepCopy() *RobotDevSuiteSpec {
	if in == nil {
		return nil
	}
	out := new(RobotDevSuiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotDevSuiteStatus) DeepCopyInto(out *RobotDevSuiteStatus) {
	*out = *in
	out.RobotVDIStatus = in.RobotVDIStatus
	out.RobotIDEStatus = in.RobotIDEStatus
	out.RemoteIDERelayServerStatus = in.RemoteIDERelayServerStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotDevSuiteStatus.
func (in *RobotDevSuiteStatus) DeepCopy() *RobotDevSuiteStatus {
	if in == nil {
		return nil
	}
	out := new(RobotDevSuiteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotIDE) DeepCopyInto(out *RobotIDE) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotIDE.
func (in *RobotIDE) DeepCopy() *RobotIDE {
	if in == nil {
		return nil
	}
	out := new(RobotIDE)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RobotIDE) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotIDEList) DeepCopyInto(out *RobotIDEList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RobotIDE, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotIDEList.
func (in *RobotIDEList) DeepCopy() *RobotIDEList {
	if in == nil {
		return nil
	}
	out := new(RobotIDEList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RobotIDEList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotIDESpec) DeepCopyInto(out *RobotIDESpec) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotIDESpec.
func (in *RobotIDESpec) DeepCopy() *RobotIDESpec {
	if in == nil {
		return nil
	}
	out := new(RobotIDESpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotIDEStatus) DeepCopyInto(out *RobotIDEStatus) {
	*out = *in
	out.PodStatus = in.PodStatus
	out.ServiceStatus = in.ServiceStatus
	out.IngressStatus = in.IngressStatus
	out.ServiceExportStatus = in.ServiceExportStatus
	out.CustomPortServiceStatus = in.CustomPortServiceStatus
	out.CustomPortIngressStatus = in.CustomPortIngressStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotIDEStatus.
func (in *RobotIDEStatus) DeepCopy() *RobotIDEStatus {
	if in == nil {
		return nil
	}
	out := new(RobotIDEStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotList) DeepCopyInto(out *RobotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Robot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotList.
func (in *RobotList) DeepCopy() *RobotList {
	if in == nil {
		return nil
	}
	out := new(RobotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RobotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotSpec) DeepCopyInto(out *RobotSpec) {
	*out = *in
	in.RobotConfig.DeepCopyInto(&out.RobotConfig)
	out.EnvironmentConfig = in.EnvironmentConfig
	out.Storage = in.Storage
	out.RobotDevSuiteTemplate = in.RobotDevSuiteTemplate
	in.WorkspaceManagerTemplate.DeepCopyInto(&out.WorkspaceManagerTemplate)
	if in.AdditionalConfigs != nil {
		in, out := &in.AdditionalConfigs, &out.AdditionalConfigs
		*out = make(map[string]AdditionalConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.RootDNSConfig = in.RootDNSConfig
	out.TLSSecretReference = in.TLSSecretReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotSpec.
func (in *RobotSpec) DeepCopy() *RobotSpec {
	if in == nil {
		return nil
	}
	out := new(RobotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotStatus) DeepCopyInto(out *RobotStatus) {
	*out = *in
	if in.PersistentDirectories != nil {
		in, out := &in.PersistentDirectories, &out.PersistentDirectories
		*out = make([]PersistentDirectory, len(*in))
		copy(*out, *in)
	}
	if in.HostDirectories != nil {
		in, out := &in.HostDirectories, &out.HostDirectories
		*out = make([]HostDirectory, len(*in))
		copy(*out, *in)
	}
	out.DiscoveryServerStatus = in.DiscoveryServerStatus
	out.ROSBridgeStatus = in.ROSBridgeStatus
	out.LoaderJobStatus = in.LoaderJobStatus
	out.WorkspaceManagerStatus = in.WorkspaceManagerStatus
	out.RobotDevSuiteStatus = in.RobotDevSuiteStatus
	in.AttachedBuildObject.DeepCopyInto(&out.AttachedBuildObject)
	if in.AttachedLaunchObjects != nil {
		in, out := &in.AttachedLaunchObjects, &out.AttachedLaunchObjects
		*out = make([]AttachedLaunchObject, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AttachedDevObjects != nil {
		in, out := &in.AttachedDevObjects, &out.AttachedDevObjects
		*out = make([]AttachedDevObject, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotStatus.
func (in *RobotStatus) DeepCopy() *RobotStatus {
	if in == nil {
		return nil
	}
	out := new(RobotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotVDI) DeepCopyInto(out *RobotVDI) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotVDI.
func (in *RobotVDI) DeepCopy() *RobotVDI {
	if in == nil {
		return nil
	}
	out := new(RobotVDI)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RobotVDI) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotVDIList) DeepCopyInto(out *RobotVDIList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RobotVDI, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotVDIList.
func (in *RobotVDIList) DeepCopy() *RobotVDIList {
	if in == nil {
		return nil
	}
	out := new(RobotVDIList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RobotVDIList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotVDISpec) DeepCopyInto(out *RobotVDISpec) {
	*out = *in
	out.Resources = in.Resources
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotVDISpec.
func (in *RobotVDISpec) DeepCopy() *RobotVDISpec {
	if in == nil {
		return nil
	}
	out := new(RobotVDISpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RobotVDIStatus) DeepCopyInto(out *RobotVDIStatus) {
	*out = *in
	out.PodStatus = in.PodStatus
	out.ServiceTCPStatus = in.ServiceTCPStatus
	out.ServiceUDPStatus = in.ServiceUDPStatus
	out.IngressStatus = in.IngressStatus
	out.PVCStatus = in.PVCStatus
	out.CustomPortServiceStatus = in.CustomPortServiceStatus
	out.CustomPortIngressStatus = in.CustomPortIngressStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RobotVDIStatus.
func (in *RobotVDIStatus) DeepCopy() *RobotVDIStatus {
	if in == nil {
		return nil
	}
	out := new(RobotVDIStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RootDNSConfig) DeepCopyInto(out *RootDNSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RootDNSConfig.
func (in *RootDNSConfig) DeepCopy() *RootDNSConfig {
	if in == nil {
		return nil
	}
	out := new(RootDNSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Step) DeepCopyInto(out *Step) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Step.
func (in *Step) DeepCopy() *Step {
	if in == nil {
		return nil
	}
	out := new(Step)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StepStatus) DeepCopyInto(out *StepStatus) {
	*out = *in
	out.Resource = in.Resource
	in.Step.DeepCopyInto(&out.Step)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StepStatus.
func (in *StepStatus) DeepCopy() *StepStatus {
	if in == nil {
		return nil
	}
	out := new(StepStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Storage) DeepCopyInto(out *Storage) {
	*out = *in
	out.StorageClassConfig = in.StorageClassConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Storage.
func (in *Storage) DeepCopy() *Storage {
	if in == nil {
		return nil
	}
	out := new(Storage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClassConfig) DeepCopyInto(out *StorageClassConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClassConfig.
func (in *StorageClassConfig) DeepCopy() *StorageClassConfig {
	if in == nil {
		return nil
	}
	out := new(StorageClassConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageMetrics) DeepCopyInto(out *StorageMetrics) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageMetrics.
func (in *StorageMetrics) DeepCopy() *StorageMetrics {
	if in == nil {
		return nil
	}
	out := new(StorageMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageStatus) DeepCopyInto(out *StorageStatus) {
	*out = *in
	if in.Usage != nil {
		in, out := &in.Usage, &out.Usage
		*out = make(map[string]StorageUsage, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageStatus.
func (in *StorageStatus) DeepCopy() *StorageStatus {
	if in == nil {
		return nil
	}
	out := new(StorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageUsage) DeepCopyInto(out *StorageUsage) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageUsage.
func (in *StorageUsage) DeepCopy() *StorageUsage {
	if in == nil {
		return nil
	}
	out := new(StorageUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSSecretReference) DeepCopyInto(out *TLSSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSSecretReference.
func (in *TLSSecretReference) DeepCopy() *TLSSecretReference {
	if in == nil {
		return nil
	}
	out := new(TLSSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Usage) DeepCopyInto(out *Usage) {
	*out = *in
	in.GPUDeviceStatuses.DeepCopyInto(&out.GPUDeviceStatuses)
	if in.GPUInstanceUsage != nil {
		in, out := &in.GPUInstanceUsage, &out.GPUInstanceUsage
		*out = make(map[string]GPUInstanceStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Network.DeepCopyInto(&out.Network)
	in.Storage.DeepCopyInto(&out.Storage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Usage.
func (in *Usage) DeepCopy() *Usage {
	if in == nil {
		return nil
	}
	out := new(Usage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Workspace) DeepCopyInto(out *Workspace) {
	*out = *in
	if in.Repositories != nil {
		in, out := &in.Repositories, &out.Repositories
		*out = make(map[string]Repository, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Workspace.
func (in *Workspace) DeepCopy() *Workspace {
	if in == nil {
		return nil
	}
	out := new(Workspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceManager) DeepCopyInto(out *WorkspaceManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceManager.
func (in *WorkspaceManager) DeepCopy() *WorkspaceManager {
	if in == nil {
		return nil
	}
	out := new(WorkspaceManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceManagerInstanceStatus) DeepCopyInto(out *WorkspaceManagerInstanceStatus) {
	*out = *in
	out.Resource = in.Resource
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceManagerInstanceStatus.
func (in *WorkspaceManagerInstanceStatus) DeepCopy() *WorkspaceManagerInstanceStatus {
	if in == nil {
		return nil
	}
	out := new(WorkspaceManagerInstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceManagerList) DeepCopyInto(out *WorkspaceManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkspaceManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceManagerList.
func (in *WorkspaceManagerList) DeepCopy() *WorkspaceManagerList {
	if in == nil {
		return nil
	}
	out := new(WorkspaceManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceManagerSpec) DeepCopyInto(out *WorkspaceManagerSpec) {
	*out = *in
	if in.Workspaces != nil {
		in, out := &in.Workspaces, &out.Workspaces
		*out = make([]Workspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceManagerSpec.
func (in *WorkspaceManagerSpec) DeepCopy() *WorkspaceManagerSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceManagerStatus) DeepCopyInto(out *WorkspaceManagerStatus) {
	*out = *in
	out.ClonerJobStatus = in.ClonerJobStatus
	out.CleanupJobStatus = in.CleanupJobStatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceManagerStatus.
func (in *WorkspaceManagerStatus) DeepCopy() *WorkspaceManagerStatus {
	if in == nil {
		return nil
	}
	out := new(WorkspaceManagerStatus)
	in.DeepCopyInto(out)
	return out
}
