# permissions for end users to edit codeeditors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: codeeditor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: robot-operator
    app.kubernetes.io/part-of: robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: codeeditor-editor-role
rules:
- apiGroups:
  - robot.roboscale.io
  resources:
  - codeeditors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robot.roboscale.io
  resources:
  - codeeditors/status
  verbs:
  - get
