# permissions for end users to edit ros2bridges.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ros2bridge-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: robot-operator
    app.kubernetes.io/part-of: robot-operator
    app.kubernetes.io/managed-by: kustomize
  name: ros2bridge-editor-role
rules:
- apiGroups:
  - robot.roboscale.io
  resources:
  - ros2bridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robot.roboscale.io
  resources:
  - ros2bridges/status
  verbs:
  - get
