apiVersion: robot.roboscale.io/v1alpha1
kind: Robot
metadata:
  labels:
    robolaunch.io/organization: boston-uni
    robolaunch.io/team: robotics
    robolaunch.io/region: usa-boston
    robolaunch.io/cloud-instance: robot01
    robolaunch.io/robot-image-user: "robolaunchio"
    robolaunch.io/robot-image-repository: "arcelik-robot"
    robolaunch.io/robot-image-tag: "foxy-agnostic-xfce"
  name: arcelik-robot
spec:
  distro: foxy
  storage:
    amount: 30000
    storageClassConfig:
      name: openebs-hostpath
      accessMode: ReadWriteOnce
  discoveryServerTemplate:
    attached: true
    hostname: "xxx"
    subdomain: "yyy"
  rosBridgeTemplate:
    ros:
      enabled: false
      distro: noetic
    ros2:
      enabled: true
      distro: foxy
    image: robolaunchio/foxy-noetic-bridge:v0.0.3
  robotDevSuiteTemplate:
    vdiEnabled: true
    ideEnabled: true
    robotVDITemplate:
      serviceType: NodePort
      ingress: false
      privileged: false
      webrtcPortRange: "31016-31019"
    robotIDETemplate:
      serviceType: NodePort
      ingress: false
      privileged: false
  buildManagerTemplate:
    steps:
    - name: rosdep
      workspace: ws-1
      command: cd $WORKSPACES_PATH/ws-1 && source /opt/ros/foxy/setup.bash && apt-get update && rosdep update && rosdep install --from-path src --ignore-src -y -r
    - name: external
      workspace: ws-1
      script: |
        #!/bin/bash
        set -eux
        pip install odrive pyserial;
        apt-key adv --keyserver keyserver.ubuntu.com --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key F6E65AC044F831AC80A06380C8B3A55A6F3EFCDE;
        apt-get install software-properties-common -y;
        add-apt-repository "deb https://librealsense.intel.com/Debian/apt-repo $(lsb_release -cs) main" -u;
        apt-get install librealsense2-dkms librealsense2-utils -y;
    - name: build
      workspace: ws-1
      command: cd $WORKSPACES_PATH/ws-1 && source /opt/ros/foxy/setup.bash && colcon build --symlink-install
  launchManagerTemplates:
  - launch:
      slam:
        selector:
          robolaunch.io/physical-instance: demo
        workspace: ws-1
        repository: repo1
        namespacing: false
        launchFilePath: slam/launch/arcelik_slam.launch.py
      slam2:
        selector:
          robolaunch.io/cloud-instance: robot01
        workspace: ws-1
        repository: repo1
        namespacing: false
        launchFilePath: slam/launch/arcelik_slam.launch.py
  workspacesPath: /root/workspaces
  workspaces:
  - name: ws-1
    repositories:
      repo1:
        url: "https://bitbucket.org/kaesystems/arcelik-ros2-odrive-mecanum"
        branch: main