apiVersion: robot.roboscale.io/v1alpha1
kind: Notebook
metadata:
  labels:
    app.kubernetes.io/name: notebook
    app.kubernetes.io/instance: notebook-sample
    app.kubernetes.io/part-of: robot-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: robot-operator
  name: notebook-sample
spec:
  # TODO(user): Add fields here
