apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "robot-operator.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "robot-operator.fullname" . }}-serving-cert
  labels:
  {{- include "robot-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "robot-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-robot-roboscale-io-v1alpha1-notebook
  failurePolicy: Fail
  name: vnotebook.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - notebooks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "robot-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-robot-roboscale-io-v1alpha1-robotide
  failurePolicy: Fail
  name: vrobotide.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robotides
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "robot-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-robot-roboscale-io-v1alpha1-robotvdi
  failurePolicy: Fail
  name: vrobotvdi.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robotvdis
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "robot-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-robot-roboscale-io-v1alpha1-robotdevsuite
  failurePolicy: Fail
  name: vrobotdevsuite.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robotdevsuites
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "robot-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-robot-roboscale-io-v1alpha1-workspacemanager
  failurePolicy: Fail
  name: vworkspacemanager.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workspacemanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "robot-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-robot-roboscale-io-v1alpha1-buildmanager
  failurePolicy: Fail
  name: vbuildmanager.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - buildmanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "robot-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-robot-roboscale-io-v1alpha1-launchmanager
  failurePolicy: Fail
  name: vlaunchmanager.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - launchmanagers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "robot-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-robot-roboscale-io-v1alpha1-robot
  failurePolicy: Fail
  name: vrobot.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - robots
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "robot-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-robot-roboscale-io-v1alpha1-discoveryserver
  failurePolicy: Fail
  name: vdiscoveryserver.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - discoveryservers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "robot-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-robot-roboscale-io-v1alpha2-ros2workload
  failurePolicy: Fail
  name: vros2workload.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - ros2workloads
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "robot-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /validate-robot-roboscale-io-v1alpha2-ros2bridge
  failurePolicy: Fail
  name: vros2bridge.kb.io
  rules:
  - apiGroups:
    - robot.roboscale.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - ros2bridges
  sideEffects: None