# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/robot.roboscale.io_robots.yaml
- bases/robot.roboscale.io_discoveryservers.yaml
- bases/robot.roboscale.io_rosbridges.yaml
- bases/robot.roboscale.io_buildmanagers.yaml
- bases/robot.roboscale.io_launchmanagers.yaml
- bases/robot.roboscale.io_robotdevsuites.yaml
- bases/robot.roboscale.io_robotvdis.yaml
- bases/robot.roboscale.io_robotides.yaml
- bases/robot.roboscale.io_robotartifacts.yaml
- bases/robot.roboscale.io_metricscollectors.yaml
- bases/robot.roboscale.io_workspacemanagers.yaml
- bases/multicluster.x-k8s.io_serviceexports.yaml
- bases/multicluster.x-k8s.io_serviceimports.yaml
- bases/robot.roboscale.io_metricsexporters.yaml
- bases/robot.roboscale.io_relayservers.yaml
- bases/robot.roboscale.io_notebooks.yaml
- bases/robot.roboscale.io_ros2workloads.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
- patches/webhook_in_robots.yaml
#- patches/webhook_in_discoveryservers.yaml
#- patches/webhook_in_rosbridges.yaml
- patches/webhook_in_buildmanagers.yaml
- patches/webhook_in_launchmanagers.yaml
- patches/webhook_in_robotdevsuites.yaml
- patches/webhook_in_robotvdis.yaml
#- patches/webhook_in_robotides.yaml
#- patches/webhook_in_robotartifacts.yaml
- patches/webhook_in_metricscollectors.yaml
- patches/webhook_in_workspacemanagers.yaml
#- patches/webhook_in_metricsexporters.yaml
- patches/webhook_in_relayservers.yaml
#- patches/webhook_in_notebooks.yaml
#- patches/webhook_in_ros2workloads.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_robots.yaml
#- patches/cainjection_in_discoveryservers.yaml
#- patches/cainjection_in_rosbridges.yaml
- patches/cainjection_in_buildmanagers.yaml
- patches/cainjection_in_launchmanagers.yaml
- patches/cainjection_in_robotdevsuites.yaml
- patches/cainjection_in_robotvdis.yaml
#- patches/cainjection_in_robotides.yaml
#- patches/cainjection_in_robotartifacts.yaml
- patches/cainjection_in_metricscollectors.yaml
- patches/cainjection_in_workspacemanagers.yaml
#- patches/cainjection_in_metricsexporters.yaml
# - patches/cainjection_in_relayservers.yaml
#- patches/cainjection_in_notebooks.yaml
#- patches/cainjection_in_ros2workloads.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
