processor:
  ignoreTypes:
    - "List$"
  sortKinds:
    - "Robot"
    - "WorkspaceManager"
    - "BuildManager"
    - "LaunchManager"
    - "RobotDevSuite"
    - "MetricsExporter"
    - "RobotVDI"
    - "Notebook"
    - "RobotIDE"
    - "DiscoveryServer"
    - "ROSBridge"
    - "RelayServer"
    - "RobotArtifact"
  ignoreFields:
    - "TypeMeta$"

render:
  kubernetesVersion: 1.22
